name: apotek_uts
description: Aplikasi apotek untuk UTS
publish_to: 'none'
version: 1.0.0+1
environment:
  sdk: ">=2.18.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  provider: ^6.0.5
  shared_preferences: ^2.2.2

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/images/welcome_bg.jpg
    - assets/images/welcome_bg_alt1.png
    - assets/images/welcome_bg_alt2.png
    - assets/images/obat_paracetamol.png
    - assets/images/obat_amoxicillin.png
    - assets/images/obat_vitamin.png
